executable            = find_tridents

output                = out/mc_sf4_$(ProcId).out
error                 = err/mc_sf4_$(ProcId).err
log                   = log/mc_sf4_$(ProcId).log

getenv                = False
notification          = Never
requirements          = (OpSysAndVer =?= "AlmaLinux9")
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files  = find_tridents, ../pythonHelpers, ../scripts, ../parFiles, ../gallery.json, /afs/cern.ch/user/i/idioniso/ddfUtils, sndswEnv.sh

max_retries           = 3

+JobFlavour           = "workday"
+AccountingGroup      = "group_u_SNDLHC.users"

queue arguments from args_mc_only_sf4.txt
