executable            = find_tridents

output                = out/tridents_all_sf4_$(ProcId).out
error                 = err/tridents_all_sf4_$(ProcId).err
log                   = log/tridents_all_sf4_$(ProcId).log

getenv                = False
notification          = Never
requirements          = (OpSysAndVer =?= "AlmaLinux9")
should_transfer_files = IF_NEEDED

max_retries           = 3

+JobFlavour           = "testmatch"
+AccountingGroup      = "group_u_SNDLHC.users"

queue arguments from args_sf4.txt
