executable            = find_tridents

output                = out/tridents_$(ProcId).out
error                 = err/tridents_$(ProcId).err
log                   = log/tridents_$(ProcId).log

getenv                = False
notification          = Never
requirements          = (OpSysAndVer =?= "AlmaLinux9")
should_transfer_files = IF_NEEDED

max_retries           = 3

+JobFlavour           = "espresso"
+AccountingGroup      = "group_u_SNDLHC.users"

queue arguments from arguments-gallery.txt
