executable            = find_tridents_2

output                = out/in_gallery_$(ProcId).out
error                 = err/in_gallery_$(ProcId).err
log                   = log/in_gallery_$(ProcId).log

getenv                = False
notification          = Never
requirements          = (OpSysAndVer =?= "AlmaLinux9")
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files  = find_tridents, ../pythonHelpers, ../scripts, ../parFiles, ../gallery.json, /afs/cern.ch/user/i/idioniso/ddfUtils, sndswEnv.sh

max_retries           = 3

+JobFlavour           = "longlunch"
+AccountingGroup      = "group_u_SNDLHC.users"

queue arguments from args_gallery_only.txt
