executable            = find_tridents

output                = out/after-cuts/tridents_$(ProcId).out
error                 = err/after-cuts/tridents_$(ProcId).err
log                   = log/after-cuts/tridents_$(ProcId).log

getenv                = False
notification          = Never
requirements          = (OpSysAndVer =?= "AlmaLinux9")
should_transfer_files = IF_NEEDED

max_retries           = 3

+JobFlavour           = "espresso"
+AccountingGroup      = "group_u_SNDLHC.users"

queue arguments from args_after-cuts.txt
