executable            = run_tridentSample.sh

output                = out/tridentSample/trimuon_boost100_signal_$(ClusterId).$(ProcId).out
error                 = err/tridentSample/trimuon_boost100_signal_$(ClusterId).$(ProcId).err
log                   = log/tridentSample/trimuon_boost100_signal_$(ClusterId).log

getenv                = False
notification          = Never
requirements          = (OpSysAndVer =?= "AlmaLinux9")
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files  = run_tridentSample.sh, ../build/bin/tridentSample, ../build/lib/libtrident_cuts.so, ../build/lib/libtrident_cuts_rdict.pcm, ../build/lib/libtrident_cuts.rootmap, sndswEnv.sh

max_retries           = 3

+JobFlavour           = "espresso"
+AccountingGroup      = "group_u_SNDLHC.users"

queue arguments from args_trimuon_boost100_signal_cutset8_tridentSample.txt
