executable            = run_tridentSample.sh

output                = out/tridentSample_.$(ClusterId).$(ProcId).out
error                 = err/tridentSample_.$(ClusterId).$(ProcId).err
#log                   = log/tridentSample/cuts7_$(ProcId).log
log                   = log/tridentSample_$(ClusterId).log

getenv                = False
notification          = Never
requirements          = (OpSysAndVer =?= "AlmaLinux9")
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files  = run_tridentSample.sh, ../build/bin/tridentSample, ../build/lib/libtrident_cuts.so, ../build/lib/libtrident_cuts_rdict.pcm, ../build/lib/libtrident_cuts.rootmap, sndswEnv.sh

max_retries           = 3

+JobFlavour           = "workday"
+AccountingGroup      = "group_u_SNDLHC.users"

queue arguments from args_run6640_tridentSample.txt
