executable            = run_hough_reco_subtasks.sh
arguments             = $(input_file) $(geo_file) $(par_file) $(start_ev) $(n_ev) $(out_file)

output                = out/houghLines/hough_run6640_looseCuts_$(ProcId).out
error                 = err/houghLines/hough_run6640_looseCuts_$(ProcId).err
log                   = log/houghLines/hough_run6640_looseCuts_$(ProcId).log

getenv                = False
notification          = Never
requirements          = (OpSysAndVer =?= "AlmaLinux9")

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files  = sndswEnv.sh, TrackingParams_sf4.xml, /afs/cern.ch/work/i/idioniso/sndMuTri/hough_line_reco.py

max_retries           = 3

+JobFlavour           = "testmatch"
+AccountingGroup      = "group_u_SNDLHC.users"

queue input_file, geo_file, par_file, start_ev, n_ev, out_file from args_run6640_features.txt
