executable            = run_hough_reco_subtasks.sh
arguments             = $(input_file) $(geo_file) $(par_file) $(start_ev) $(n_ev) $(out_file)

output                = out/houghLines/hough_trimuon_cutset8_$(ClusterId).$(ProcId).out
error                 = err/houghLines/hough_trimuon_cutset8_$(ClusterId).$(ProcId).err
log                   = log/houghLines/hough_trimuon_cutset8_$(ClusterId).log

getenv                = False
notification          = Never
requirements          = (OpSysAndVer =?= "AlmaLinux9")

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files  = sndswEnv.sh, TrackingParams_sf4.xml, /afs/cern.ch/work/i/idioniso/sndMuTri/hough_line_reco.py

max_retries           = 3

+JobFlavour           = "tomorrow"
+AccountingGroup      = "group_u_SNDLHC.users"

queue input_file, geo_file, par_file, start_ev, n_ev, out_file from args_trimuon_boost100_cutset8_hough.txt
