executable            = find_tridents

output                = out/__tridents_all_$(ProcId).out
error                 = err/__tridents_all_$(ProcId).err
log                   = log/__tridents_all_$(ProcId).log

getenv                = False
notification          = Never
requirements          = (OpSysAndVer =?= "AlmaLinux9")
should_transfer_files = IF_NEEDED

max_retries           = 3

+JobFlavour           = "testmatch"
+AccountingGroup      = "group_u_SNDLHC.users"

queue arguments from args_tmp.txt
