include_directories(BEFORE ${CMAKE_CURRENT_SOURCE_DIR})

# Header files for dictionary generation
set(ANALYSIS_HEADERS
  TridentTruthProcessor.h
  PreselectionProcessor.h
  MuonCalibrationProcessor.h
  PassingMuonTruthProcessor.h
  DigiValidationProcessor.h
  DataManager.h
  ProgressPrinter.h
)

set(ANALYSIS_SRCS
  TridentTruthProcessor.cxx
  PreselectionProcessor.cxx
  MuonCalibrationProcessor.cxx
  PassingMuonTruthProcessor.cxx
  DigiValidationProcessor.cxx
  DataManager.cxx
  ProgressPrinter.cxx
)

# ROOT generate dictionary
root_generate_dictionary(G__trident_analysis
  ${ANALYSIS_HEADERS}
  LINKDEF AnalysisLinkDef.h
)

# Add library for analysis
add_library(trident_analysis SHARED
  ${ANALYSIS_SRCS}
  G__trident_analysis.cxx
)

# Find sndsw dependencies
find_library(SHIP_DATA_LIB ShipData PATHS "${SNDSW_ROOT}/lib" NO_DEFAULT_PATH REQUIRED)
find_library(SHIP_LHC_LIB shipLHC PATHS "${SNDSW_ROOT}/lib" NO_DEFAULT_PATH REQUIRED)
find_library(ANALYSIS_TOOLS_LIB snd_analysis_tools PATHS "${SNDSW_ROOT}/lib" NO_DEFAULT_PATH REQUIRED)

target_link_libraries(trident_analysis
  PUBLIC
    ROOT::Core
    ROOT::Tree
    ROOT::ROOTDataFrame
    ROOT::RIO
    ROOT::Hist
    ROOT::Geom
    ${SHIP_DATA_LIB}
    ${SHIP_LHC_LIB}
    ${ANALYSIS_TOOLS_LIB}
)
